spring:
  datasource:
    username: ${EXPENSE_TRACKER_DB_USER}
    password: ${EXPENSE_TRACKER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${EXPENSE_TRACKER_DB_HOST}:${EXPENSE_TRACKER_DB_PORT}/${EXPENSE_TRACKER_DB_NAME}
logging:
  level:
    org:
      springframework:
        security: debug